watdiv: 
  exec: "docker exec watdiv watdiv"
  #exec: "watdiv"
product:
  template: "bsbm-product.template"
  scale_factor: 1
  params:
    # type
    product_id: 1000
    producer_n: 12
    feature_n: 20
    prod_type: 10
    # pgroup
    productPropertyTextual4_p: 0.7
    productPropertyTextual5_p: 0.8
    productPropertyNumeric4_p: 0.7
    productPropertyNumeric5_p: 0.8

    # assocation
  test:
    - "test_assc_products-producer.sparql"

vendor:
  template: "bsbm-vendor.template"
  scale_factor: 1
  params:
    product_n: ${product.params.product_id}
    offer_n: 15
    #vendor_n: 10

person:
  template: "bsbm-person.template"
  scale_factor: 1
  params:
    #type
    product_n: ${product.params.product_id}
    review_n: 14
    #pgroup
    rating1_p: 0.7
    rating2_p: 0.7
    rating3_p: 0.7
    rating4_p: 0.7