product:
  template: "bsbm-product.template"
  scale_factor: 1
  params:
    # type
    product_id: 100
    producer_n: 4
    feature_n: 6
    prod_type: 2
    # pgroup
    # assocation
  test:
    - "test_assc_products-producer.sparql"

vendor:
  template: "bsbm-vendor.template"
  scale_factor: 1
  params:
    product_n: ${product.params.product_id}
    offer_n: 10
    #vendor_n: 10

offer:
  template: "bsbm-offer.template"
  scale_factor: 1
  params:
    product_n: ${product.params.product_n}
    offer_n: 10
