# Expectation: should get a zipfian distribution

SELECT ?shop (COUNT(DISTINCT ?offer) as ?nbOffer)
WHERE {
    GRAPH ?shop {
        ?offer ?p ?o .
        FILTER(REGEX(?offer, "Offer[0-9]+$"))
    }
}
GROUP BY ?shop
ORDER BY ASC (?shop)