# Expectation: should get a zipfian distribution
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT ?feature2 ?feature1 (COUNT(DISTINCT ?shop) as ?nbShop)
WHERE {
    GRAPH ?shop {
        ?offer bsbm:product ?product .
        ?product bsbm:productFeature ?feature1 .
        ?product bsbm:productFeature ?feature2 .
        FILTER (?feature1 != ?feature2) .
    }
}
GROUP BY ?feature1 ?feature2
ORDER BY DESC (?nbShop)