# Expectation: should get a zipfian distribution
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT ?type (COUNT(DISTINCT ?shop) as ?nbShop)
WHERE {
    GRAPH ?shop {
        ?offer bsbm:product ?product .
        ?product a ?type .
    }
}
GROUP BY ?type
ORDER BY DESC (?nbShop)