# Expectation: should get a zipfian distribution
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT 
    ?product
    ?ProductFeature1  
    (COUNT(DISTINCT ?shop) as ?nbShop)
    (GROUP_CONCAT(DISTINCT ?shop, "|") as ?candidateShop)
WHERE {
    GRAPH ?shop {
        ?offer bsbm:product ?product .
        ?product bsbm:productFeature ?ProductFeature1 .
    }
}
GROUP BY ?product ?ProductFeature1