PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT 
    ?ProductXYZ 
    (COUNT(DISTINCT ?person) as ?nbPerson)
    (GROUP_CONCAT(DISTINCT ?shop, "|") as ?candidatePerson)
WHERE { 
    # const ?ProductXYZ
	?review bsbm:reviewFor ?ProductXYZ .
}
GROUP BY ?ProductXYZ