PREFIX rev: <http://purl.org/stuff/rev#>

SELECT
    ?ReviewXYZ
    (COUNT(DISTINCT ?person) as ?nbPerson)
    (GROUP_CONCAT(DISTINCT ?person, "|") as ?candidatePerson)
WHERE { 
    # const ?ReviewXYZ
    GRAPH ?person {
        ?ReviewXYZ rev:reviewer ?x 
    }
}
GROUP BY ?ReviewXYZ