# Expectation: should get 1 everywhere
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT ?offre (COUNT(DISTINCT ?vendor) as ?nbVendor)
WHERE {
    GRAPH ?shop {
        ?offre bsbm:vendor ?vendor .
    }
}
GROUP BY ?offre
ORDER BY ASC (?offre)